### ISSUE TITLE
SPFX for Sharepoint 2019

### ISSUE THREAD

**Issue by mpamaral72** [SharePoint/sp-dev-training-spfx-react-fabric#23]
I don't know if this would be the correct channel for this question but... Is there any Microsoft team plan to update SPFX to Sharepoint 2019? Currently we can only use version 1.4.1 with React 15 yet.

**Comment by andrewconnell** [comment]
This issue list is only for the content in this module, not for product questions. Best to direct those to the [sp-dev-docs](/sharepoint/sp-dev-docs) issue list.
